# High-Tech Solutions Internal DNS settings
domain-needed
bogus-priv
listen-address=127.0.0.1,192.168.20.10
expand-hosts
domain=hightech.local

# Fix: Points to the Nginx Proxy (Web Server)
address=/gitea.hightech.local/192.168.20.10
